name: point-nerf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.8.1=py38_cu102
  - torchvision=0.9.1=py38_cu102
  - cudatoolkit=10.2
  - kornia=0.5.11+cu102
  - scipy
  - scikit-image
  - matplotlib
  - opencv
  - imageio
  - tqdm
  - pandas
  - jupyter